#%RAML 1.0 ResourceType

  get:
    description: recuperation des données <<resourcePathName>>
    responses:
      200:
        body:
          application/json:
            example: |
              <<exampleReponse1>>